ZEN_EXAMPLES = [
    [
        "A beautiful landscape with mountains and a lake",
        "imgs/style1.png",
        "imgs/structure1.png",
        "imgs/output1.png",
        20,
        0.4,
        0.6,
        30,
    ],
     [
         "girl with a dragon",
         "imgs/structure2.jpg",
         "imgs/style2.jpg",
         "imgs/output2.png",
         15,
         0.8,
         0.7,
         28,
     ],
    [
         "a flying whale airplane with some trees growing on it",
         "imgs/structure3.webp",
         "imgs/style3.png",
         "imgs/output3.png",
         15,
         0.65,
         0.53,
         28,
     ],
    [
         "a flying whale airplane with some trees growing on it",
         "imgs/structure3.webp",
         "imgs/style4.png",
         "imgs/output4.png",
         15,
         0.65,
         0.5,
         28,
     ],
    [
         "a startrooper playing with a robot by a window",
         "imgs/structure5.webp",
         "imgs/style5.webp",
         "imgs/output5.png",
         15,
         0.8,
         0.6,
         28,
     ],
]
